#!/usr/bin/env bash
#Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx
name=$(hostname)
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        add_header X-Served-By $name always;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name myafc.tech;

	error_page 404 /error_404.html;

	location = /error_404.html {
		root /var/www/html;
		internal;
	}

        location /redirect_me {
                return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
        }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
