#!/usr/bin/env bash
#This script pings any IP address give to it as an arguement

if [ "$1" == "" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
else
    ping -c 5 "$1"
fi
