#!/usr/bin/env bash
# this script lists all the process containing bash

for pid_dir in /proc/[0-9]*
do
    process_name=$(tr -d '\0' < "$pid_dir/cmdline")
    if [[ $process_name == *bash* ]]
    then
        pid=$(basename "$pid_dir")
        echo $pid $process_name
    fi
done
