#!/usr/bin/env bash
# This script prints Fizz if the number is divisible by 5, Buzz if it's divisible by 3 and fizzbuss if it's divisible by both.

for number in {1..100}
do
    if ((number % 3 == 0 && number % 5 == 0));
    then
        echo "FizzBuzz"
    elif ((number % 3 == 0));
    then
        echo "Fizz"
    elif ((number%5 == 0));
    then
        echo "Buzz"
    else
        echo "$number"
    fi
done
