#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop but badluck at 4th iteration and good luck at 8th iteration.

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    count=$((count+1)) # Increment count by 1.
done
