#!/usr/bin/env bash
# This script checks if a file or directory named school is present in the pwd.

file_path=school

if [[ -e $file_path ]]
then
    echo "school file exists"
    if [[ -s $file_path ]]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [[ -f $file_path ]]
    then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi
