#!/usr/bin/env bash

contents_of_pwd="$(ls ./)"
for content in $contents_of_pwd
do
    if [[ $content == *-* ]]
    then
        new_content=$(echo "$content" | sed -e 's/[^-]*-//')
        echo $new_content
    fi
done

contents_of_pwd="$(ls ./)"
for content in $contents_of_pwd
do
    if [[ $content == *-* ]]
    then
        new_content=$(echo "$content" | sed -e 's/^[^-]*-//')
        echo $new_content
    fi
done

#!/usr/bin/env bash

contents_of_pwd="$(ls ./)"
for content in $contents_of_pwd
do
    if [[ $content == *-* ]]
    then
        new_content=$(echo "$content" | sed -e 's/.*-//')
        echo $new_content
    fi
done